package com.base.Republic.wsclient.data.apws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-08-07T14:34:08.253+02:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "IListaAp")
@XmlSeeAlso({com.base.Republic.wsclient.data.serialization.ObjectFactory.class, ObjectFactory.class, com.base.Republic.wsclient.data.request.ObjectFactory.class, com.base.Republic.wsclient.data.apws.ObjectFactory.class})
public interface IListaAp {

    @WebMethod(operationName = "GetRegListaEntiteta", action = "http://tempuri.org/IListaAp/GetRegListaEntiteta")
    @Action(input = "http://tempuri.org/IListaAp/GetRegListaEntiteta", output = "http://tempuri.org/IListaAp/GetRegListaEntitetaResponse")
    @RequestWrapper(localName = "GetRegListaEntiteta", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetRegListaEntiteta")
    @ResponseWrapper(localName = "GetRegListaEntitetaResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetRegListaEntitetaResponse")
    @WebResult(name = "GetRegListaEntitetaResult", targetNamespace = "http://tempuri.org/")
    public com.base.Republic.wsclient.data.request.ResponseMessage getRegListaEntiteta(
        @WebParam(name = "data", targetNamespace = "http://tempuri.org/")
        com.base.Republic.wsclient.data.response.TAprZahtev data
    );
}
